package com.krishifarms.mobile.core.security.rbac

/**
 * Mobile permission strings — must match backend permission_catalog.py and RBAC plan §5.1.
 */
enum class Permission(val code: String) {
    FARMER_VIEW("FARMER_VIEW"),
    FARMER_CREATE("FARMER_CREATE"),
    FARMER_UPDATE("FARMER_UPDATE"),
    FARMER_DELETE("FARMER_DELETE"),

    FARM_VIEW("FARM_VIEW"),
    FARM_CREATE("FARM_CREATE"),
    FARM_UPDATE("FARM_UPDATE"),
    FARM_DELETE("FARM_DELETE"),

    PROCUREMENT_VIEW("PROCUREMENT_VIEW"),
    PROCUREMENT_CREATE("PROCUREMENT_CREATE"),
    PROCUREMENT_UPDATE("PROCUREMENT_UPDATE"),
    PROCUREMENT_APPROVE("PROCUREMENT_APPROVE"),
    PROCUREMENT_DELETE("PROCUREMENT_DELETE"),

    EXPENSE_VIEW("EXPENSE_VIEW"),
    EXPENSE_CREATE("EXPENSE_CREATE"),
    EXPENSE_UPDATE("EXPENSE_UPDATE"),
    EXPENSE_APPROVE("EXPENSE_APPROVE"),
    EXPENSE_DELETE("EXPENSE_DELETE"),

    PAYMENT_VIEW("PAYMENT_VIEW"),
    PAYMENT_CREATE("PAYMENT_CREATE"),
    PAYMENT_APPROVE("PAYMENT_APPROVE"),
    PAYMENT_DELETE("PAYMENT_DELETE"),

    COLLECTION_VIEW("COLLECTION_VIEW"),
    COLLECTION_CREATE("COLLECTION_CREATE"),
    COLLECTION_UPDATE("COLLECTION_UPDATE"),

    WORKER_VIEW("WORKER_VIEW"),
    WORKER_CREATE("WORKER_CREATE"),
    WORKER_UPDATE("WORKER_UPDATE"),
    WORKER_DELETE("WORKER_DELETE"),

    WORK_ORDER_VIEW("WORK_ORDER_VIEW"),
    WORK_ORDER_CREATE("WORK_ORDER_CREATE"),
    WORK_ORDER_UPDATE("WORK_ORDER_UPDATE"),
    WORK_ORDER_COMPLETE("WORK_ORDER_COMPLETE"),

    ATTENDANCE_VIEW("ATTENDANCE_VIEW"),
    ATTENDANCE_UPDATE("ATTENDANCE_UPDATE"),

    DOCUMENT_VIEW("DOCUMENT_VIEW"),
    DOCUMENT_CREATE("DOCUMENT_CREATE"),
    DOCUMENT_DELETE("DOCUMENT_DELETE"),

    REPORT_VIEW("REPORT_VIEW"),
    REPORT_EXPORT("REPORT_EXPORT"),

    SETTINGS_VIEW("SETTINGS_VIEW"),
    SETTINGS_MANAGE("SETTINGS_MANAGE"),
    USER_MANAGE("USER_MANAGE"),
    SYNC_MANAGE("SYNC_MANAGE"),

    VEHICLE_VIEW("VEHICLE_VIEW"),
    TRIP_VIEW("TRIP_VIEW"),
    ASSET_VIEW("ASSET_VIEW"),
    RENTAL_VIEW("RENTAL_VIEW"),
    ;

    companion object {
        fun fromCode(code: String): Permission? =
            entries.firstOrNull { it.code.equals(code, ignoreCase = true) }

        fun fromCodes(codes: Collection<String>): Set<Permission> =
            codes.mapNotNull { fromCode(it) }.toSet()

        fun all(): Set<Permission> = entries.toSet()
    }
}
